In [1]:
import numpy as np

In [10]:
a = np.array([[1,2,3,3,1],
               [6,8,11,10,7]]).T

In [11]:
a.shape

(5, 2)

In [12]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = a.mean(axis=0)

In [15]:
mean_a

array([2. , 8.4])

In [16]:
a_centered = a - mean_a

In [17]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [18]:
a_centered[:,1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [26]:
a_centered[:,0]

array([-1.,  0.,  1.,  1., -1.])

In [27]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [28]:
a_centered_sp

8.0

In [30]:
a_centered_sp/(a.shape[0]-1)

2.0

In [34]:
np.cov(a.T)[0,1]

2.0