## ** Задание на повторение материала

#### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [1]:
import numpy as np

In [4]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [11]:
a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)
a3 = a.reshape(6, 2)
a4 = a.reshape(2, 6)
a5 = a.reshape(12, 1)

#### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [12]:
a1 = a.reshape(-1, 4)
a2 = a.reshape(-1, 3)
a3 = a.reshape(-1, 2)
a4 = a.reshape(2, -1)
a5 = a.reshape(12, -1)

In [16]:
a5.ndim

2

#### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Нет, так как каждый элемент такого массива - тоже массив

In [17]:
a5.ndim

2

#### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [33]:
b = np.random.randn(3, 4)

In [20]:
b.size

12

In [26]:
c = b.flatten()

In [23]:
c.size

12

#### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [31]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [36]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

разница только в том, что во 2м случае у нас двумерный массив (массив в массиве)

#### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [41]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis = 0)
v.size

10

#### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [45]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
A = a.reshape(4,3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [52]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [53]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [54]:
B.size

16

In [56]:
np.linalg.det(B)

0.0

Определитель матрицы равен нулю, значит вычислить обратную матрицу для матрицы B нельзя

#### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [63]:
np.random.seed(42)

#### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [67]:
c = np.random.randint(0, 16, (16))
print(c)

[ 7  2  5  4  1  7 11 13  5  1 15 11  4  0 11  9]


#### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [73]:
C = c.reshape(4, 4)
print(C)

[[ 7  2  5  4]
 [ 1  7 11 13]
 [ 5  1 15 11]
 [ 4  0 11  9]]


In [75]:
D = C * 10 + B
print(D)

[[ 75  34  73  72]
 [ 24 120 196 252]
 [ 73  96 299 322]
 [ 72 122 322 392]]


In [76]:
np.linalg.det(D)

33790400.00000005

In [77]:
np.linalg.matrix_rank(D)

4

In [79]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.01610043 -0.00531689 -0.00816208  0.00716535]
 [ 0.00715114  0.02249692  0.00430063 -0.01930844]
 [-0.0055933   0.00488364  0.03278919 -0.02904612]
 [-0.00058833 -0.01003658 -0.02677328  0.03110351]]


#### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [85]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
print(D_inv)

[[1. 0. 0. 1.]
 [1. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 1.]]


In [83]:
ind = np.where(D_inv)

In [99]:
E = C.copy()


array([[ 7,  2,  5,  4],
       [ 1,  7, 11, 13],
       [ 5,  1, 15, 11],
       [ 4,  0, 11,  9]])

In [102]:
E[ind] = B[ind]
print(E)

[[  5   2   5  32]
 [ 14  50  86  13]
 [  5  86 149  11]
 [  4   0  11 302]]
